// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kv_request.grpc.proto
// Protobuf C++ Version: 5.27.0-dev

#include "kv_request.grpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr KVRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        request_type_{static_cast< ::KVRequest_RequestType >(0)},
        key_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR KVRequest::KVRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct KVRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KVRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~KVRequestDefaultTypeInternal() {}
  union {
    KVRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KVRequestDefaultTypeInternal _KVRequest_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_kv_5frequest_2egrpc_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_kv_5frequest_2egrpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_kv_5frequest_2egrpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::KVRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::KVRequest, _impl_.request_type_),
        PROTOBUF_FIELD_OFFSET(::KVRequest, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::KVRequest, _impl_.value_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::KVRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_KVRequest_default_instance_._instance,
};
const char descriptor_table_protodef_kv_5frequest_2egrpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025kv_request.grpc.proto\"\202\001\n\tKVRequest\022,\n"
    "\014request_type\030\001 \001(\0162\026.KVRequest.RequestT"
    "ype\022\013\n\003key\030\002 \001(\005\022\r\n\005value\030\003 \001(\t\"+\n\013Reque"
    "stType\022\007\n\003GET\020\000\022\007\n\003PUT\020\001\022\n\n\006DELETE\020\002b\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_kv_5frequest_2egrpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_kv_5frequest_2egrpc_2eproto = {
    false,
    false,
    164,
    descriptor_table_protodef_kv_5frequest_2egrpc_2eproto,
    "kv_request.grpc.proto",
    &descriptor_table_kv_5frequest_2egrpc_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_kv_5frequest_2egrpc_2eproto::offsets,
    file_level_enum_descriptors_kv_5frequest_2egrpc_2eproto,
    file_level_service_descriptors_kv_5frequest_2egrpc_2eproto,
};
const ::google::protobuf::EnumDescriptor* KVRequest_RequestType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_kv_5frequest_2egrpc_2eproto);
  return file_level_enum_descriptors_kv_5frequest_2egrpc_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t KVRequest_RequestType_internal_data_[] = {
    196608u, 0u, };
bool KVRequest_RequestType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr KVRequest_RequestType KVRequest::GET;
constexpr KVRequest_RequestType KVRequest::PUT;
constexpr KVRequest_RequestType KVRequest::DELETE;
constexpr KVRequest_RequestType KVRequest::RequestType_MIN;
constexpr KVRequest_RequestType KVRequest::RequestType_MAX;
constexpr int KVRequest::RequestType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class KVRequest::_Internal {
 public:
};

KVRequest::KVRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:KVRequest)
}
inline PROTOBUF_NDEBUG_INLINE KVRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::KVRequest& from_msg)
      : value_(arena, from.value_),
        _cached_size_{0} {}

KVRequest::KVRequest(
    ::google::protobuf::Arena* arena,
    const KVRequest& from)
    : ::google::protobuf::Message(arena) {
  KVRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, request_type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, request_type_),
           offsetof(Impl_, key_) -
               offsetof(Impl_, request_type_) +
               sizeof(Impl_::key_));

  // @@protoc_insertion_point(copy_constructor:KVRequest)
}
inline PROTOBUF_NDEBUG_INLINE KVRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void KVRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, request_type_),
           0,
           offsetof(Impl_, key_) -
               offsetof(Impl_, request_type_) +
               sizeof(Impl_::key_));
}
KVRequest::~KVRequest() {
  // @@protoc_insertion_point(destructor:KVRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void KVRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
KVRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(KVRequest, _impl_._cached_size_),
              false,
          },
          &KVRequest::MergeImpl,
          &KVRequest::kDescriptorMethods,
          &descriptor_table_kv_5frequest_2egrpc_2eproto,
          nullptr,  // tracker
      };
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 23, 2> KVRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_KVRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::KVRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .KVRequest.RequestType request_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(KVRequest, _impl_.request_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(KVRequest, _impl_.request_type_)}},
    // int32 key = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(KVRequest, _impl_.key_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(KVRequest, _impl_.key_)}},
    // string value = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(KVRequest, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .KVRequest.RequestType request_type = 1;
    {PROTOBUF_FIELD_OFFSET(KVRequest, _impl_.request_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 key = 2;
    {PROTOBUF_FIELD_OFFSET(KVRequest, _impl_.key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string value = 3;
    {PROTOBUF_FIELD_OFFSET(KVRequest, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\11\0\0\5\0\0\0\0"
    "KVRequest"
    "value"
  }},
};

PROTOBUF_NOINLINE void KVRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:KVRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  ::memset(&_impl_.request_type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.key_) -
      reinterpret_cast<char*>(&_impl_.request_type_)) + sizeof(_impl_.key_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* KVRequest::_InternalParse(const char* ptr,
                                        ::_pbi::ParseContext* ctx) {
  return ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
}

::uint8_t* KVRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:KVRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .KVRequest.RequestType request_type = 1;
  if (this->_internal_request_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_request_type(), target);
  }

  // int32 key = 2;
  if (this->_internal_key() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_key(), target);
  }

  // string value = 3;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "KVRequest.value");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KVRequest)
  return target;
}

::size_t KVRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KVRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string value = 3;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  // .KVRequest.RequestType request_type = 1;
  if (this->_internal_request_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_request_type());
  }

  // int32 key = 2;
  if (this->_internal_key() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_key());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void KVRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<KVRequest*>(&to_msg);
  auto& from = static_cast<const KVRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:KVRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_request_type() != 0) {
    _this->_impl_.request_type_ = from._impl_.request_type_;
  }
  if (from._internal_key() != 0) {
    _this->_impl_.key_ = from._impl_.key_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void KVRequest::CopyFrom(const KVRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KVRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool KVRequest::IsInitialized() const {
  return true;
}

void KVRequest::InternalSwap(KVRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(KVRequest, _impl_.key_)
      + sizeof(KVRequest::_impl_.key_)
      - PROTOBUF_FIELD_OFFSET(KVRequest, _impl_.request_type_)>(
          reinterpret_cast<char*>(&_impl_.request_type_),
          reinterpret_cast<char*>(&other->_impl_.request_type_));
}

::google::protobuf::Metadata KVRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_kv_5frequest_2egrpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
